### ISSUE TITLE
Code Review Tools

### ISSUE THREAD

**Issue by bfj5889** [TeamGarnet/Garnet_Main_Repo#2]
Look for some good code review tools that have the following criteria:
Free
Used with GIT
Possibly used with Slack
Can possibly require acceptance before being pushed.

**Comment by danquack** [comment]
The way it’s done in industry is everyone creates their own private forks and then creates Pull requests. These pull requests are then approved or denied by the team. There also can be notification within slack and team members can make comments before Code is merged in. 

--
Daniel Quackenbush
Rochester Institute of Technology
Computer and Information Technologies '18

**Comment by bfj5889** [comment]
The way I have seen it done in industry is slightly different.
I have seen that everyone will make their own branch for a feature and once their feature is complete they use a code review tool like Smartbear Collaboration to basically create diffs of all the files that were changed between their branch and the master. 
It also gives people a place to comment on and easily see what was changed. 
Then once the review has been completed the member can merge their branch into master/production.
Most tools can be integrated into GIT and allow you to set reviewers.

**Comment by axk4545** [comment]
@bfj5889 @danquack I think that github has the code review tools you mentioned. If you want I can help configure them since I know them and that kinda fits with my sysadmin role

**Comment by axk4545** [comment]
@bfj5889 I will need more access to set it up. Feel free to revoke after it is configured.

**Comment by axk4545** [comment]
@bfj5889 please check that it functions the way you want and if so I will close this.

**Comment by bfj5889** [comment]
This can be closed
