### ISSUE TITLE
Determine wire framing tool

### ISSUE THREAD

**Issue by bfj5889** [TeamGarnet/Garnet_Main_Repo#4]

**Comment by colejohnson** [comment]
Draw.io or Figma would be a good space for collaboration.

**Comment by bfj5889** [comment]
@colejohnson go ahead and accept the invite to the gitHub so I can assign this task to you

**Comment by colejohnson** [comment]
Are we all set up on Figma?

**Comment by bfj5889** [comment]
I made the account and added everyone as admin, but havent done anything past that point. So if there was any structure you wanted in place its all up to you.
